# Spring配置
spring:
  application:
    name: pzen-springboot-17-demo #当前项目名称
  profiles:
    active: dev #当前项目运行环境 dev（开发者）、test（测试）、prod（生产）
  # 资源信息
  messages:
    basename: i18n/messages # 国际化资源文件路径
  # 文件上传
  servlet:
    multipart:
      max-file-size: 10MB # 单个文件大小
      max-request-size: 20MB # 设置总上传的文件大小
  # 服务模块
  devtools:
    restart:
      enabled: true # 热部署开关
  # redis 配置
  data:
    redis:
      host: 192.168.50.3  # 地址
      port: 6379 # 端口，默认为6379
      database: 1 # 数据库索引
      password: Qq122076344  # 密码
      timeout: 3s # 连接超时时间
      lettuce:
        pool:
          min-idle: 0 # 连接池中的最小空闲连接
          max-idle: 8 # 连接池中的最大空闲连接
          max-active: 8 # 连接池的最大数据库连接数
          max-wait: 1000ms # #连接池最大阻塞等待时间（使用负值 -1ms 表示没有限制）

server:
  port: 8443
  http-port: 8080
  servlet:
    context-path: / # 应用的访问路径
  http2:
    enabled: true
  #使用Undertow配置localhost.jks 具体配置方式请到/pathSSL/生成本地测试的SSL秘钥和证书.txt中查看
  ssl:
    enabled: true
    key-store: ./pathSSL/localhost.jks
    key-alias: localhost
    key-store-type: JKS
    key-store-password: localhost # 秘钥库密码
    key-password: localhost # 如果与密钥库密码不同，填写证书私钥的密码；否则可以省略，使用密钥库密码作为默认值
  undertow:
    buffer-size: 16KB # 缓冲区大小 根据网络带宽和请求响应数据大小调整
    max-http-post-size: 10MB  # 根据实际情况调整，避免恶意请求利用大头攻击
    threads:
      io: 8 # 线程池最大线程数 CPU核心数
      worker: 256 # 线程池最大线程数







# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接 原/system/*,/monitor/*,/tool/*
  urlPatterns: /*


# 日志配置
logging:
  level:
    com.pzen: debug
    org.springframework: warn
  file:
    path: logs
  logback:
    rollingpolicy:
      max-history: 14
      max-file-size: 10MB


#自定义配置
my:
  # 路由过滤配置
  permitStatus: true # 是否开启路由拦截 true为开启 false为关闭
  urls: # 需要放开的URL
    - /test/user/list

